export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';


export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';

export const FETCH_START = 'FETCH_START';
export const FETCH_STORE = 'FETCH_STORE';
export const FETCH_FAIL = 'FETCH_FAIL';


//login------------------------------------------
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_STORE = 'LOGIN_STORE';
export const PROFILE_STORE = 'PROFILE_STORE';
export const LOGIN_END = 'LOGIN_END'
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const LOGIN_BROKE = 'LOGIN_BROKE';




export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_END = 'SIGNUP_END';
export const SIGNUP_CONFLICT = 'SIGNUP_CONFLICT';


export const PROFILE_EDIT_START = 'PROFILE_EDIT';
export const PROFILE_SAVE_START = 'PROFILE_START_SAVE';
export const PROFILE_SAVE_END = 'PROFILE_STARTEND';
export const PROFILE_SAVE_FAILED = 'PROFILE_SAVE_FAILED';
export const PROFILE_EDIT_END = 'PROFILE_EDIT_END';



